---
- hosts: vyos
  gather_facts: false

  tasks:
    - name: show hostname
      debug:
       msg: "{{ inventory_hostname }}"

    - name: restore configuration
      vyos_config:
        src: "/tmp/backup/{{ inventory_hostname }}_config"
